package com.github.scausidc.stellaria.letter.model;
// Generated 2015/10/01 13:51:14 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * IncomeLetter generated by hbm2java
 */
public class IncomeLetter extends Letter
    implements java.io.Serializable {

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        IncomeLetter c = (IncomeLetter)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }

}


