package com.github.scausidc.stellaria.letter.model;
// Generated 2015/10/01 13:51:14 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Letter generated by hbm2java
 */
public class Letter  implements java.io.Serializable {


    protected Long id;
    protected String remote;
    protected String content;
    protected String msgType;
    protected Date tm;

    protected String clazz;

    public Letter() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRemote() {
        return this.remote;
    }

    public void setRemote(String remote) {
        this.remote = remote;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMsgType() {
        return this.msgType;
    }

    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    public Date getTm() {
        return this.tm;
    }

    public void setTm(Date tm) {
        this.tm = tm;
    }

    public String getClazz() {
        return this.clazz;
    }

    public void setClazz(String clazz) {
        this.clazz = clazz;
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        Letter c = (Letter)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }

}


