package com.github.scausidc.stellaria.letter.model;
// Generated 2015/10/01 13:51:14 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * LetterSession generated by hbm2java
 */
public class LetterSession  implements java.io.Serializable {


    protected Long id;
    protected String openid;
    protected Date lastReceive;
    protected Date lastRead;
    protected Date lastReply;
    protected Boolean archived;

    public LetterSession() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public Date getLastReceive() {
        return this.lastReceive;
    }

    public void setLastReceive(Date lastReceive) {
        this.lastReceive = lastReceive;
    }

    public Date getLastRead() {
        return this.lastRead;
    }

    public void setLastRead(Date lastRead) {
        this.lastRead = lastRead;
    }

    public Date getLastReply() {
        return this.lastReply;
    }

    public void setLastReply(Date lastReply) {
        this.lastReply = lastReply;
    }

    public Boolean isArchived() {
        return this.archived;
    }

    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

  // HASH
    @Override
    public int hashCode()
    {
        int hash = 17;

        if (this.id != null)
            hash = hash * 31 + this.id.hashCode();

        return(hash);
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return(true);

        if (o==null || !this.getClass().equals(o.getClass()))
            return(false);

        LetterSession c = (LetterSession)o;

        return(
            (this.id == c.id) ||
            (this.id != null && this.id.equals(c.id))
        );
    }



}


